//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReview
    {
        public int ReviewId { get; set; }
        public int ProId { get; set; }
        public int AccId { get; set; }
        public int Rating { get; set; }
        public string Comment { get; set; }
        public DateTime ReviewDate { get; set; }

        public virtual Account Account { get; set; }
        public virtual Product Product { get; set; }
    }
}
